/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectionRouteImport } from './routes/inspection'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfsRouteImport } from './routes/ofs'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesArticleIdRouteImport } from './routes/articles.$articleId'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRoute = InspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfsRoute = OfsRouteImport.update({
  id: '/ofs',
  path: '/ofs',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesArticleIdRoute = ArticlesArticleIdRouteImport.update({
  id: '/articles/$articleId',
  path: '/articles/$articleId',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/ofs': typeof OfsRoute
  '/scan': typeof ScanRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/ofs': typeof OfsRoute
  '/scan': typeof ScanRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/machines': typeof MachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspection': typeof InspectionRoute
  '/login': typeof LoginRoute
  '/ofs': typeof OfsRoute
  '/scan': typeof ScanRoute
  '/articles/$articleId': typeof ArticlesArticleIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/inspection'
    | '/login'
    | '/ofs'
    | '/scan'
    | '/articles/$articleId'
    | '/articles/'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inspection'
    | '/login'
    | '/ofs'
    | '/scan'
    | '/articles/$articleId'
    | '/articles'
    | '/machines'
  id:
    | '__root__'
    | '/'
    | '/inspection'
    | '/login'
    | '/ofs'
    | '/scan'
    | '/articles/$articleId'
    | '/articles/'
    | '/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectionRoute: typeof InspectionRoute
  LoginRoute: typeof LoginRoute
  OfsRoute: typeof OfsRoute
  ScanRoute: typeof ScanRoute
  ArticlesArticleIdRoute: typeof ArticlesArticleIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection': {
      id: '/inspection'
      path: '/inspection'
      fullPath: '/inspection'
      preLoaderRoute: typeof InspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofs': {
      id: '/ofs'
      path: '/ofs'
      fullPath: '/ofs'
      preLoaderRoute: typeof OfsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$articleId': {
      id: '/articles/$articleId'
      path: '/articles/$articleId'
      fullPath: '/articles/$articleId'
      preLoaderRoute: typeof ArticlesArticleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectionRoute: InspectionRoute,
  LoginRoute: LoginRoute,
  OfsRoute: OfsRoute,
  ScanRoute: ScanRoute,
  ArticlesArticleIdRoute: ArticlesArticleIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  MachinesIndexRoute: MachinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
